export enum Locations {
  WICK = 'WICK',
  ABERDEEN = 'ABERDEEN',
  EDINBURGH = 'EDINBURGH',
  BELFAST = 'BELFAST',
  MANCHESTER = 'MANCHESTER',
  CARDIFF = 'CARDIFF',
  PLYMOUTH = 'PLYMOUTH',
  LONDON = 'LONDON',
}

export enum Days {
  MON = 'MON',
  TUE = 'TUE',
  WED = 'WED',
  THU = 'THU',
  FRI = 'FRI',
  SAT = 'SAT',
  SUN = 'SUN',
}

export enum Direction {
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  TOP = 'TOP',
  BOTTOM = 'BOTTOM',
}

export enum WeatherIconUrls {
  CLEAR_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/clear-night@2x1.png',
  SUNNY_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Sunny.png',
  PARTLY_CLOUDY_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Party-Cloudy.png',
  PARTLY_CLOUDY_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Party-Cloudy.png',
  MIST = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/foggy@2x1.png',
  FOG = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/foggy@2x1.png',
  CLOUDY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Cloudy.png',
  OVERCAST = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Cloudy.png',
  LIGHT_RAIN_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Rain2.png',
  LIGHT_RAIN_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Rain2.png',
  DRIZZLE = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Rain2.png',
  LIGHT_RAIN = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Rain2.png',
  HEAVY_RAIN_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Rain2.png',
  HEAVY_RAIN_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Rain2.png',
  HEAVY_RAIN = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Rain2.png',
  SLEET_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  SLEET_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  SLEET = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  HAIL_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Hail.png',
  HAIL_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Hail.png',
  HAIL = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Hail.png',
  LIGHT_SNOW_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  LIGHT_SNOW_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  LIGHT_SNOW = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  HEAVY_SNOW_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  HEAVY_SNOW_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  HEAVY_SNOW = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Snow.png',
  THUNDER_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Storm.png',
  THUNDER_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Storm.png',
  THUNDER = 'https://www.thesun.co.uk/wp-content/uploads/2018/11/Storm.png',
}

export enum WeatherAtmosphereUrls {
  CLEAR_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_clearnight@2x.jpg',
  SUNNY_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_sunny@2x.jpg',
  PARTLY_CLOUDY_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_partlycloudynight@2x.jpg',
  PARTLY_CLOUDY_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_partlycloudynight@2x.jpg',
  MIST = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_foggy@2x.jpg',
  FOG = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_foggy@2x.jpg',
  CLOUDY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_cloudy@2x.jpg',
  OVERCAST = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_cloudy@2x.jpg',
  LIGHT_RAIN_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  LIGHT_RAIN_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  DRIZZLE = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  LIGHT_RAIN = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  HEAVY_RAIN_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  HEAVY_RAIN_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  HEAVY_RAIN = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  SLEET_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  SLEET_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  SLEET = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  HAIL_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  HAIL_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  HAIL = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_raining@2x.jpg',
  LIGHT_SNOW_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  LIGHT_SNOW_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  LIGHT_SNOW = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  HEAVY_SNOW_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  HEAVY_SNOW_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  HEAVY_SNOW = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_snowing@2x.jpg',
  THUNDER_SHOWER_NIGHT = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_stormy@2x.jpg',
  THUNDER_SHOWER_DAY = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_stormy@2x.jpg',
  THUNDER = 'https://www.thesun.co.uk/wp-content/uploads/2018/08/BG_stormy@2x.jpg',
}
